# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user = User.create! :email => 'guy@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user = User.create! :email => 'keirl@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret', :confirmed_at => Time.now
user = User.create! :email => 'kourtney@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret', :confirmed_at => Time.now
user4 = User.create! :email => 'akila@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret', :confirmed_at => Time.now
user11 = User.create! :email => 'jackson@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user12 = User.create! :email => 'zoe@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user13 = User.create! :email => 'aria@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user14 = User.create! :email => 'aiden@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user15 = User.create! :email => 'skyler@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user16 = User.create! :email => 'lucy@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user17 = User.create! :email => 'john@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user18 = User.create! :email => 'grace@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user19 = User.create! :email => 'liam@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user20 = User.create! :email => 'sophia@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user21 = User.create! :email => 'emma@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user22 = User.create! :email => 'olivia@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user23 = User.create! :email => 'ava@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user24 = User.create! :email => 'mia@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user25 = User.create! :email => 'madison@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user26 = User.create! :email => 'lucas@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now
user27 = User.create! :email => 'logan@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret',:confirmed_at => Time.now

Profile.create(user_name: 'akila3',
               gender: 1,
               is_a_smoker: 1,
               pet_friendly: 1,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               has_residence_already: true,
               street: '500 Riverside drive',
               city: 'New York',
               state: 'NY',
               postal_code: '10027',
               user_id: user4.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'jackson',
               gender: 1,
               is_a_smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user11.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user11.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'zoe',
               gender: 2,
               is_a_smoker: 1,
               pet_friendly: 2,
               cleanliness_level: 2,
               outgoingness_level: 2,
               quietness_level: 2,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user12.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user12.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'aria',
               gender: 2,
               is_a_smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 3,
               outgoingness_level: 3,
               quietness_level: 3,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user13.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user13.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'aiden',
               gender: 1,
               is_a_smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 4,
               outgoingness_level: 4,
               quietness_level: 4,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user14.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user14.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'skyler',
               gender: 2,
               is_a_smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 5,
               outgoingness_level: 5,
               quietness_level: 5,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user15.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user15.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'lucy',
               gender: 2,
               is_a_smoker: 1,
               pet_friendly: 2,
               cleanliness_level: 1,
               outgoingness_level: 3,
               quietness_level: 5,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user16.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 2,
               smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user16.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'john',
               gender: 1,
               is_a_smoker: 2,
               pet_friendly: 2,
               cleanliness_level: 5,
               outgoingness_level: 2,
               quietness_level: 4,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user17.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user17.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'grace',
               gender: 2,
               is_a_smoker: 2,
               pet_friendly: 2,
               cleanliness_level: 2,
               outgoingness_level: 1,
               quietness_level: 5,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user18.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user18.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'liam',
               gender: 1,
               is_a_smoker: 1,
               pet_friendly: 1,
               cleanliness_level: 3,
               outgoingness_level: 4,
               quietness_level: 1,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user19.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 1,
               outgoingness_level: 1,
               quietness_level: 1,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user19.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'sophia',
               gender: 2,
               is_a_smoker: 1,
               pet_friendly: 2,
               cleanliness_level: 3,
               outgoingness_level: 4,
               quietness_level: 1,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user20.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 1,
               pet_friendly: 2,
               cleanliness_level: 2,
               outgoingness_level: 3,
               quietness_level: 4,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user20.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'emma',
               gender: 2,
               is_a_smoker: 2,
               pet_friendly: 2,
               cleanliness_level: 3,
               outgoingness_level: 4,
               quietness_level: 5,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user21.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 1,
               pet_friendly: 2,
               cleanliness_level: 2,
               outgoingness_level: 3,
               quietness_level: 2,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user21.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'olivia',
               gender: 2,
               is_a_smoker: 1,
               pet_friendly: 1,
               cleanliness_level: 3,
               outgoingness_level: 4,
               quietness_level: 5,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user22.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 1,
               pet_friendly: 1,
               cleanliness_level: 5,
               outgoingness_level: 1,
               quietness_level: 2,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user22.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'ava',
               gender: 2,
               is_a_smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 3,
               outgoingness_level: 4,
               quietness_level: 5,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user23.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 2,
               smoker: 2,
               pet_friendly: 2,
               cleanliness_level: 3,
               outgoingness_level: 3,
               quietness_level: 3,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user23.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'mia',
               gender: 2,
               is_a_smoker: 1,
               pet_friendly: 2,
               cleanliness_level: 3,
               outgoingness_level: 3,
               quietness_level: 4,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user24.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 2,
               smoker: 1,
               pet_friendly: 2,
               cleanliness_level: 2,
               outgoingness_level: 3,
               quietness_level: 4,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user24.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'madison',
               gender: 2,
               is_a_smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 3,
               outgoingness_level: 3,
               quietness_level: 4,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user25.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 2,
               smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 2,
               outgoingness_level: 5,
               quietness_level: 2,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user25.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'lucas',
               gender: 1,
               is_a_smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 2,
               outgoingness_level: 3,
               quietness_level: 4,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user26.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 2,
               pet_friendly: 1,
               cleanliness_level: 4,
               outgoingness_level: 4,
               quietness_level: 4,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user26.id,
               latitude: nil,
               longitude: nil)

Profile.create(user_name: 'logan',
               gender: 1,
               is_a_smoker: 1,
               pet_friendly: 2,
               cleanliness_level: 2,
               outgoingness_level: 3,
               quietness_level: 4,
               has_residence_already: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user27.id,
               latitude: nil,
               longitude: nil)

Preferences.create(gender: 1,
               smoker: 1,
               pet_friendly: 2,
               cleanliness_level: 4,
               outgoingness_level: 3,
               quietness_level: 2,
               looking_for_residence: true,
               street: '123 lexington avenue',
               city: 'New York',
               state: 'NY',
               postal_code: '10016',
               user_id: user27.id,
               latitude: nil,
               longitude: nil)

admin = Admin.create! :email => 'admin@gmail.com', :password => 'topsecret', :password_confirmation => 'topsecret'