# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b481971e37e60c2dc78a3c4ce248060fb56975eddb9da190fabdf5d394bb766a5485412d7c7566457765fccb1a9e2f6062ff4b48da4137e7415c95fd328762e

test:
  secret_key_base: 1d0436fa7ee00a72317b96db13c3247a0cd4c46314655eb558c1d52e303800e33fee3c90a38d662316f2f18f3778fe3f9ae517270cacf755cd17df6aedc70793

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
